### ISSUE TITLE
Exception when using OpeningHours::createAndMergeOverlappingRanges

### ISSUE THREAD

**Issue by larssn** [spatie/opening-hours#140]
Doing:
```
OpeningHours::createAndMergeOverlappingRanges(
	array(
		'exceptions' => array(
			'01-01' => array(
				'hours' => array(),
				'data'  => array(
					'id' => 'my_id',
				),
			),
			'02-02' => array(
				'hours' => array(),
				'data'  => array(
					'id' => 'my_id',
				),
			),
		),
	)
);
```

Causes:
```
[18-Jun-2020 18:58:29 UTC] PHP Fatal error:  Uncaught Spatie\OpeningHours\Exceptions\InvalidTimeRangeString: The string `my_id` isn't a valid time range string. A time string must be a formatted as `H:i-H:i`, e.g. `09:00-18:00`. in spatie/opening-hours/src/Exceptions/InvalidTimeRangeString.php:9
Stack trace:
#0 spatie/opening-hours/src/TimeRange.php(31): Spatie\OpeningHours\Exceptions\InvalidTimeRangeString::forString('my_id')
#1 spatie/opening-hours/src/OpeningHours.php(78): Spatie\OpeningHours\TimeRange::fromString('my_id')
#2 spatie/opening-hours/src/OpeningHours.php(77): Spatie\OpeningHours\OpeningHours::mergeOverlappingRanges(Array)
#3 spatie/opening-hours/src/Exceptions/InvalidTimeRangeString.php on line 9
```

**Comment by kylekatarnls** [comment]
Thanks for your report. It's now fixed in 2.7.2.
